a1 = float(input("What's a1? "))
b1 = float(input("What's b1? "))
c1 = float(input("What's c1? "))
a2 = float(input("What's a2? "))
b2 = float(input("What's b2? "))
c2 = float(input("What's c2? "))
xanswer = ((b2*c1)-(b1*c1))/((a1*b2)-(a2*b2))
yanswer = ((a1*c2)-(a2*c1))/((a1*b2)-(a2*b2))
print ("X is %s, and Y is %s." % (xanswer, yanswer))
